//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesProjectWebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DistributorEntities : DbContext
    {
        public DistributorEntities()
            : base("name=DistributorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
<<<<<<< Updated upstream:SalesProjectWebApi/userModel.Context.cs
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<Authorizer_Profile> Authorizer_Profiles { get; set; }
=======
        public DbSet<tbl_DistributorLoginDetails> tbl_DistributorLoginDetails { get; set; }
>>>>>>> Stashed changes:SalesProjectWebApi/DistributorsDB.Context.cs
    }
}
